// A printable manual, typeset from the published documentation. The request carries the whole
// document in `data` and the logo as a `files` entry, so this template holds only presentation:
// a cover, a running header and footer, a table of contents, and one rule per content block.
//
// `data` is generated by scripts/manual_content.py from docs/ and mkdocs.yml, which is why the
// manual cannot drift from the site it is made of.

#let accent = rgb("#3f51b5")
#let shade = rgb("#f4f4f8")

// One inline span. These four kinds are all the converter emits.
#let span-content(span) = {
  if span.kind == "code" {
    raw(span.text)
  } else if span.kind == "strong" {
    strong(span.text)
  } else if span.kind == "link" {
    link(span.href, text(fill: accent, span.text))
  } else if span.kind == "ref" {
    // A link to another chapter of this manual rather than to the site it was made from.
    link(label(span.target), text(fill: accent, span.text))
  } else {
    span.text
  }
}

#let spans(items) = items.map(span-content).join()

#let cells(row) = row.map(cell => spans(cell))

// One content block. Headings keep the level they had on the page, so the page's own `#` becomes
// the chapter title the outline and the running header pick up.
#let content-block(item) = {
  if item.type == "heading" {
    heading(level: item.level, item.text)
  } else if item.type == "paragraph" {
    par(spans(item.spans))
  } else if item.type == "code" {
    block(
      width: 100%,
      fill: shade,
      inset: 8pt,
      radius: 3pt,
      breakable: true,
      text(size: 7.5pt, raw(item.text, lang: if item.language != "" { item.language })),
    )
  } else if item.type == "list" {
    list(..item.items.map(entry => spans(entry)))
  } else if item.type == "table" {
    block(breakable: true, table(
      columns: item.header.len(),
      stroke: (x, y) => if y == 0 { (bottom: 0.6pt + accent) } else { (bottom: 0.2pt + luma(200)) },
      inset: 6pt,
      table.header(..cells(item.header).map(cell => strong(cell))),
      ..item.rows.map(row => cells(row)).flatten(),
    ))
  }
}

// Two faces travel with the request, and only their Medium and Bold cuts, so every rule that
// selects one names one of those weights; asking for a weight that is absent would silently fall
// back to the body face.
#let display = "Space Grotesk" // headings
#let wordmark = "Inter Display" // the name and its tagline on the cover

#set text(size: 10pt)
#set par(justify: true, leading: 0.65em)
#show heading: set text(font: display)
#show heading.where(level: 1): set text(size: 17pt, weight: "bold", fill: accent)
#show heading.where(level: 2): set text(size: 12pt, weight: "medium")
#show heading.where(level: 3): set text(size: 10.5pt, weight: "medium")
#show heading: set block(above: 1.4em, below: 0.7em)
#show raw.where(block: false): set text(size: 9pt)

// Cover. Its own page rule keeps the header and footer off the first sheet.
#page(margin: 2.5cm, header: none, footer: none)[
  #v(3.5cm)
  // The mark ends 32 units above the bottom of its 256-unit viewBox, so bottom-aligning the boxes
  // would leave the name sitting below the mark it is set against. Lifting the text column by that
  // same proportion puts the two on one baseline whatever the logo is scaled to.
  #let logo-width = 62mm
  #let logo-clearance = logo-width * 32 / 256
  #grid(
    columns: (auto, 1fr),
    column-gutter: 12mm,
    align: (left + bottom, left + bottom),
    image(data.logo, width: logo-width),
    {
      // Measured by the glyph outlines rather than by the baseline: the tagline ends in descenders,
      // and aligning a baseline with the mark's hard edge leaves those hanging below it, which is
      // what the eye reads as "slightly too low".
      set text(font: wordmark, top-edge: "bounds", bottom-edge: "bounds")
      // Paragraph spacing would stack on top of the explicit gap below, so the lockup states its
      // own: the distance between the name and its tagline is a design decision, not a leftover.
      set par(spacing: 0pt)
      text(size: 40pt, weight: "bold", tracking: -1pt)[#data.title]
      v(3.5mm)
      text(size: 14pt, weight: "medium", fill: luma(95))[#data.subtitle]
      v(logo-clearance)
    },
  )
  #v(14mm)
  #block(width: 85%, text(size: 11pt)[#data.description])
  #v(1fr)
  #text(size: 9pt, fill: luma(110))[
    #link(data.site_url, data.site_url) \
    #link(data.repo_url, data.repo_url)
  ]
]

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.2cm, x: 2.2cm),
  header: context {
    // The running header names the chapter the reader is in. Selection is by page number rather
    // than by `before(here())`: a header is laid out at the top of its page, so "before here"
    // would find the previous chapter on every page a chapter starts on.
    let current = here().page()
    let seen = query(heading.where(level: 1)).filter(item => item.location().page() <= current)
    if seen.len() > 0 {
      set text(size: 8pt, fill: luma(110))
      grid(
        columns: (1fr, auto),
        align: (left, right),
        emph(seen.last().body), data.title,
      )
      v(-6pt)
      line(length: 100%, stroke: 0.4pt + luma(200))
    }
  },
  footer: context {
    set text(size: 8pt, fill: luma(110))
    align(center, counter(page).display("1 / 1", both: true))
  },
)
#counter(page).update(1)

// The contents title is deliberately not a heading: chapters own level 1, and the running header
// above finds the current chapter by asking for exactly those.
#text(font: display, size: 17pt, weight: "bold", fill: accent)[Contents]
#v(6mm)
#outline(title: none, depth: 2)

#for chapter in data.chapters {
  pagebreak()
  // An empty anchor carrying the chapter's label, so a cross-reference in the text can jump here.
  [#metadata(chapter.id)#label(chapter.id)]
  if chapter.section != none {
    text(size: 8pt, fill: luma(130), tracking: 1pt, upper(chapter.section))
    v(-2mm)
  }
  chapter.blocks.map(content-block).join()
}
